In [1]:
#import numpy for make datas and analysis:

In [3]:
import numpy as np

In [4]:
# make an array that is grades of students in four lessons:

In [5]:
grades = np.array([[20,18,17.25,16,12,15,20,19,17.5,14.75,9,11,4.5,6,13.75,16,9.75,18.5,14,20],
                   [19,15,13,14,17,15,13,17,18,12,7.5,13,12,10,15,16,10,14,7,19.5],
                   [17,16,14,18.5,14,12.5,9,15.5,19,6.5,9,14.25,13,13,14,17,11,17,10,18.25],
                   [18.5,15,10,17,12.5,13,7,8,14,9,9,13.75,15,12.5,5,13,6,9,12,17.75]])

In [6]:
#find mean grade in lessons:

In [7]:
averageGrades = np.mean(grades, axis=1)
averageGrades

array([14.6  , 13.85 , 13.925, 11.85 ])

In [8]:
#find min grades and max grades :

In [9]:
minGrandes = np.min(averageGrades)
minLesson = np.where(averageGrades == minGrandes)
print("less score lesson",minLesson,"with",minGrandes)

less score lesson (array([3], dtype=int64),) with 11.85


In [ ]:
#find high score in lesson:

In [11]:
maxGrades = np.max(averageGrades)
maxLesson = np.where(averageGrades == maxGrades)
print("high score lesson is",maxLesson,"with",maxGrades)

high score lesson is (array([0], dtype=int64),) with 14.6


In [ ]:
#find average of students scores:

In [11]:
averageStudents = np.mean(grades, axis=0)
averageStudents

array([18.625 , 16.    , 13.5625, 16.375 , 13.875 , 13.875 , 12.25  ,
       14.875 , 17.125 , 10.5625,  8.625 , 13.    , 11.125 , 10.375 ,
       11.9375, 15.5   ,  9.1875, 14.625 , 10.75  , 18.875 ])

In [ ]:
#find best student:

In [32]:
maxStudent = np.max(averageStudents)
maxStudentll = np.where(averageStudents == maxStudent)
print("best student is", maxStudentll, "with", maxStudent)

best student is (array([19], dtype=int64),) with 18.875


In [ ]:
#find worst student:

In [33]:
minStudent = np.min(averageStudents)
minStudentll = np.where(averageStudents == minStudent)
print("worst student is", minStudentll, "with", minStudent)

worst student is (array([10], dtype=int64),) with 8.625


In [ ]:
#find worst score in all datas:

In [35]:
mingrade = np.min(grades)
mingradel = np.where(grades == mingrade)
print(mingrade, "worst score in lesson and for student", mingradel)

4.5 worst score in lesson and for student (array([0], dtype=int64), array([12], dtype=int64))


In [ ]:
#find best score in lesson:

In [36]:
maxgrade = np.max(grades)
maxgradel = np.where(grades == maxgrade)
print(maxgrade, "best score in lesson and for student", maxgradel)

20.0 best score in lesson and for student (array([0, 0, 0], dtype=int64), array([ 0,  6, 19], dtype=int64))


In [12]:
#find scores that are fewer than 10

In [37]:
scoreLess10 = grades[grades<10]
scoreLess10

array([9.  , 4.5 , 6.  , 9.75, 7.5 , 7.  , 9.  , 6.5 , 9.  , 7.  , 8.  ,
       9.  , 9.  , 5.  , 6.  , 9.  ])